# Generated by Django 3.0.7 on 2020-06-06 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTypes',
            fields=[
                ('geotype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('geotype_ru', models.CharField(max_length=100, unique=True)),
                ('geotype_en', models.CharField(max_length=100, unique=True)),
                ('geotype_description_ru', models.CharField(max_length=1000, unique=True)),
                ('geotype_description_en', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language_iso', models.CharField(max_length=3, unique=True)),
                ('language_name_ru', models.CharField(max_length=100, unique=True)),
                ('language_name_en', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotivationTypes',
            fields=[
                ('motivation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('motivation_short_name_ru', models.CharField(max_length=100, unique=True)),
                ('motivation_short_name_en', models.CharField(max_length=100, unique=True)),
                ('motivation_comment_ru', models.CharField(max_length=1000, unique=True)),
                ('motivation_comment_en', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceReferences',
            fields=[
                ('source_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_full_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeoObjects',
            fields=[
                ('geoobject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('osm_id', models.IntegerField()),
                ('geotype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.GeoTypes')),
            ],
        ),
    ]
