# Generated by Django 3.0.7 on 2020-06-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('map_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_name_ru', models.CharField(max_length=100, unique=True)),
                ('area_name_en', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoNames',
            fields=[
                ('geoname_id', models.IntegerField(primary_key=True, serialize=False)),
                ('geoname', models.CharField(max_length=200)),
                ('name_translation_ru', models.CharField(max_length=200, null=True)),
                ('name_translation_en', models.CharField(max_length=200, null=True)),
                ('motivation_comment', models.CharField(max_length=1000, null=True)),
                ('linguistic_means', models.CharField(max_length=1000, null=True)),
                ('geoobject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.GeoObjects')),
                ('language_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.Language')),
                ('motivation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.MotivationTypes')),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.SourceReferences')),
            ],
        ),
        migrations.AddField(
            model_name='geoobjects',
            name='map_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.Maps'),
        ),
    ]
