# Generated by Django 3.0.7 on 2020-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0002_auto_20200606_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='area_name_en',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='maps',
            name='area_name_ru',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
