# Generated by Django 3.0.7 on 2020-06-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0004_geoobjects_is_duplicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSystems',
            fields=[
                ('geo_system_id', models.IntegerField(primary_key=True, serialize=False)),
                ('geo_system_ru', models.CharField(max_length=200, unique=True)),
                ('geo_system_en', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
