# Generated by Django 3.0.7 on 2020-06-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0006_mapssystems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
