# Generated by Django 3.0.7 on 2020-06-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0007_auto_20200607_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonames',
            name='geoname_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geoobjects',
            name='geoobject_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geosystems',
            name='geo_system_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geotypes',
            name='geotype_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maps',
            name='map_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motivationtypes',
            name='motivation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sourcereferences',
            name='source_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
