# Generated by Django 3.0.7 on 2020-09-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0008_auto_20200607_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonames',
            name='motivation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.MotivationTypes'),
        ),
    ]
