# Generated by Django 3.0.7 on 2020-09-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0009_auto_20200922_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonames',
            name='motivation_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
