# Generated by Django 3.0.7 on 2020-09-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0010_auto_20200922_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapssystems',
            name='geo_system_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.GeoSystems'),
        ),
        migrations.AlterField(
            model_name='mapssystems',
            name='map_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.Maps'),
        ),
    ]
