# Generated by Django 3.0.7 on 2020-09-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0011_auto_20200922_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonames',
            name='geoobject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.GeoObjects'),
        ),
        migrations.AlterField(
            model_name='geonames',
            name='language_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.Language'),
        ),
        migrations.AlterField(
            model_name='geonames',
            name='linguistic_means',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='geonames',
            name='name_translation_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='geonames',
            name='name_translation_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='geonames',
            name='source_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.SourceReferences'),
        ),
        migrations.AlterField(
            model_name='geoobjects',
            name='geotype_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.GeoTypes'),
        ),
        migrations.AlterField(
            model_name='geoobjects',
            name='is_duplicate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoobjects',
            name='map_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.Maps'),
        ),
    ]
