# Generated by Django 4.1.5 on 2023-01-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0012_auto_20200922_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('editor_id', models.AutoField(primary_key=True, serialize=False)),
                ('editor_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('patronymic', models.TextField()),
                ('last_name', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='geoobjects',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geoobjects',
            name='is_coordinates_approximate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geoobjects',
            name='location_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GeoNarrationTranslations',
            fields=[
                ('geonarration_translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_translation', models.TextField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toponymic_db.language')),
            ],
        ),
        migrations.CreateModel(
            name='GeoNarrations',
            fields=[
                ('geonarration_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_original', models.TextField()),
                ('geoobject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toponymic_db.geoobjects')),
                ('narrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toponymic_db.persons')),
            ],
        ),
        migrations.AddField(
            model_name='geoobjects',
            name='editor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.editors'),
        ),
    ]
