# Generated by Django 4.1.5 on 2023-01-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0015_alter_persons_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='date_collected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='place_collected',
            field=models.TextField(blank=True, null=True),
        ),
    ]
