# Generated by Django 4.1.5 on 2023-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0016_maps_date_collected_maps_place_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
