# Generated by Django 4.1.5 on 2023-01-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0018_geonames_number_on_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoobjects',
            name='editor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toponymic_db.persons'),
        ),
        migrations.DeleteModel(
            name='Editors',
        ),
    ]
