# Generated by Django 4.1.5 on 2023-01-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0019_alter_geoobjects_editor_id_delete_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='area_name_en',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='maps',
            name='area_name_ru',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
