# Generated by Django 4.1.5 on 2023-01-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0020_alter_maps_area_name_en_alter_maps_area_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
