# Generated by Django 4.1.5 on 2023-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0021_maps_map_latitude_maps_map_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='comment_collected_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='comment_collected_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
