# Generated by Django 4.1.5 on 2023-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponymic_db', '0022_maps_comment_collected_en_maps_comment_collected_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
